version: 0.2.0.0
github: tek/polysemy-log
license: BSD-2-Clause-Patent
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "tek@tryp.io"
copyright: "2021 Torsten Schmits"
category: Logging
build-type: Simple
